/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KskIdRouteImport } from './routes/ksk.$id'
import { Route as DkjIdRouteImport } from './routes/dkj.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KskIdRoute = KskIdRouteImport.update({
  id: '/ksk/$id',
  path: '/ksk/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DkjIdRoute = DkjIdRouteImport.update({
  id: '/dkj/$id',
  path: '/dkj/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dkj/$id': typeof DkjIdRoute
  '/ksk/$id': typeof KskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dkj/$id': typeof DkjIdRoute
  '/ksk/$id': typeof KskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dkj/$id': typeof DkjIdRoute
  '/ksk/$id': typeof KskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dkj/$id' | '/ksk/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dkj/$id' | '/ksk/$id'
  id: '__root__' | '/' | '/dkj/$id' | '/ksk/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DkjIdRoute: typeof DkjIdRoute
  KskIdRoute: typeof KskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ksk/$id': {
      id: '/ksk/$id'
      path: '/ksk/$id'
      fullPath: '/ksk/$id'
      preLoaderRoute: typeof KskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dkj/$id': {
      id: '/dkj/$id'
      path: '/dkj/$id'
      fullPath: '/dkj/$id'
      preLoaderRoute: typeof DkjIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DkjIdRoute: DkjIdRoute,
  KskIdRoute: KskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
